version: '3'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/atmo_watch_server
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-Qoumz+eUaby7AC7keHu/5xmZPmrI66Yn/eGldEQKtm7ymM2gZhCs2Pu5qdDzCLVU}

volumes:
  postgres-data: {}
